"""Ticket to Ride Legacy: Legends of the West — map graph and tickets.

Route lengths are reconstructed from published board photographs
(East Coast start map + completed campaign boards). A player may claim
only one track of a double/triple route, so doubles do not change the
cost graph for a single company.
"""

REGIONS = [
    {"id": "ec", "name": "East Coast", "short": "EC", "locked": True, "color": "#2f5d8a"},
    {"id": "fl", "name": "Florida", "short": "FL", "locked": False, "color": "#3a8a7a"},
    {"id": "gp", "name": "Great Plains", "short": "GP", "locked": False, "color": "#c4a35a"},
    {"id": "or", "name": "Open Range", "short": "OR", "locked": False, "color": "#b86b3a"},
    {"id": "bl", "name": "Badlands", "short": "BL", "locked": False, "color": "#8a6b45"},
    {"id": "hw", "name": "Haunted Wastes", "short": "HW", "locked": False, "color": "#5c5c66"},
    {"id": "cs", "name": "Cascadia", "short": "CS", "locked": False, "color": "#3d7a4a"},
    {"id": "ca", "name": "California", "short": "CA", "locked": False, "color": "#c45c4a"},
    {"id": "sm", "name": "Sierra Madre", "short": "SM", "locked": False, "color": "#a45a3a"},
]

# Board-relative coordinates (viewBox 1400 x 820).
CITIES = {
    "Vancouver": {"x": 78, "y": 62, "region": "cs", "port": True},
    "Seattle": {"x": 72, "y": 118, "region": "cs", "port": True},
    "Portland": {"x": 78, "y": 168, "region": "cs"},
    "Spokane": {"x": 188, "y": 128, "region": "cs"},
    "Calgary": {"x": 248, "y": 48, "region": "cs"},
    "Helena": {"x": 268, "y": 132, "region": "cs"},
    "Sacramento": {"x": 78, "y": 268, "region": "ca"},
    "San Francisco": {"x": 38, "y": 292, "region": "ca", "port": True},
    "Pacific Haven": {"x": 36, "y": 352, "region": "ca", "port": True},
    "Nuevos Angeles": {"x": 70, "y": 412, "region": "ca", "port": True},
    "Baja": {"x": 108, "y": 468, "region": "ca", "port": True},
    "Cemetery City": {"x": 138, "y": 318, "region": "ca"},
    "Salt Lake City": {"x": 214, "y": 248, "region": "hw"},
    "Phoenix": {"x": 198, "y": 402, "region": "hw"},
    "Santa Fe": {"x": 292, "y": 372, "region": "hw"},
    "Denver": {"x": 332, "y": 268, "region": "hw"},
    "Cheyenne": {"x": 338, "y": 198, "region": "hw"},
    "Regina": {"x": 368, "y": 38, "region": "bl"},
    "Miles City": {"x": 338, "y": 112, "region": "bl"},
    "Winnipeg": {"x": 458, "y": 36, "region": "bl"},
    "Fargo": {"x": 448, "y": 118, "region": "bl"},
    "Duluth": {"x": 548, "y": 72, "region": "gp"},
    "St. Paul": {"x": 548, "y": 138, "region": "gp"},
    "Davenport": {"x": 608, "y": 198, "region": "gp"},
    "Omaha": {"x": 488, "y": 208, "region": "gp"},
    "Kansas City": {"x": 508, "y": 278, "region": "gp"},
    "St. Louis": {"x": 608, "y": 278, "region": "gp"},
    "Dodge City": {"x": 418, "y": 308, "region": "or"},
    "Oklahoma City": {"x": 458, "y": 358, "region": "or"},
    "Dallas": {"x": 478, "y": 428, "region": "or"},
    "Little Rock": {"x": 558, "y": 358, "region": "or"},
    "Houston": {"x": 528, "y": 498, "region": "or", "port": True},
    "San Antonio": {"x": 438, "y": 508, "region": "or"},
    "El Paso": {"x": 308, "y": 458, "region": "sm"},
    "Hermosillo": {"x": 198, "y": 528, "region": "sm"},
    "Chihuahua": {"x": 268, "y": 548, "region": "sm"},
    "Monterrey": {"x": 348, "y": 578, "region": "sm"},
    "Chicago": {"x": 668, "y": 178, "region": "ec"},
    "Detroit": {"x": 738, "y": 128, "region": "ec"},
    "Cincinnati": {"x": 698, "y": 248, "region": "ec"},
    "Pittsburgh": {"x": 798, "y": 168, "region": "ec"},
    "Lewisburg": {"x": 838, "y": 228, "region": "ec", "town": True},
    "Buffalo": {"x": 818, "y": 98, "region": "ec"},
    "Montreal": {"x": 888, "y": 48, "region": "ec"},
    "Quebec": {"x": 958, "y": 28, "region": "ec"},
    "Albany": {"x": 918, "y": 98, "region": "ec"},
    "Boston": {"x": 1008, "y": 88, "region": "ec", "port": True},
    "Bangor": {"x": 1058, "y": 38, "region": "ec"},
    "New York": {"x": 968, "y": 148, "region": "ec", "port": True},
    "Philadelphia": {"x": 948, "y": 198, "region": "ec", "port": True},
    "Baltimore": {"x": 898, "y": 238, "region": "ec", "port": True},
    "Norfolk": {"x": 958, "y": 298, "region": "ec", "port": True},
    "Knoxville": {"x": 768, "y": 308, "region": "ec"},
    "Nashville": {"x": 698, "y": 328, "region": "ec"},
    "Charlotte": {"x": 858, "y": 338, "region": "ec"},
    "Atlanta": {"x": 778, "y": 378, "region": "ec"},
    "Charleston": {"x": 918, "y": 378, "region": "ec", "port": True},
    "Savannah": {"x": 888, "y": 428, "region": "ec", "port": True},
    "Mobile": {"x": 728, "y": 448, "region": "ec", "port": True},
    "New Orleans": {"x": 668, "y": 498, "region": "ec", "port": True},
    "Jacksonville": {"x": 868, "y": 488, "region": "fl", "port": True},
    "Tampa": {"x": 808, "y": 548, "region": "fl", "port": True},
    "Miami": {"x": 878, "y": 588, "region": "fl", "port": True},
}

# (a, b, length, region, tracks)  tracks=1 single, 2 double
ROUTES = [
    # East Coast
    ("Quebec", "Montreal", 1, "ec", 1),
    ("Quebec", "Bangor", 2, "ec", 1),
    ("Bangor", "Boston", 2, "ec", 2),
    ("Montreal", "Buffalo", 2, "ec", 2),
    ("Montreal", "Albany", 2, "ec", 1),
    ("Buffalo", "Albany", 2, "ec", 1),
    ("Buffalo", "New York", 3, "ec", 1),
    ("Buffalo", "Detroit", 2, "ec", 2),
    ("Buffalo", "Pittsburgh", 2, "ec", 1),
    ("Albany", "Boston", 2, "ec", 1),
    ("Albany", "New York", 2, "ec", 1),
    ("Boston", "New York", 2, "ec", 2),
    ("New York", "Philadelphia", 1, "ec", 2),
    ("Philadelphia", "Baltimore", 2, "ec", 1),
    ("Philadelphia", "Norfolk", 2, "ec", 1),
    ("Baltimore", "Norfolk", 2, "ec", 1),
    ("Baltimore", "Pittsburgh", 3, "ec", 1),
    ("Baltimore", "Lewisburg", 2, "ec", 2),
    ("Baltimore", "Charlotte", 2, "ec", 1),
    ("Norfolk", "Charlotte", 2, "ec", 1),
    ("Detroit", "Chicago", 2, "ec", 1),
    ("Detroit", "Pittsburgh", 2, "ec", 1),
    ("Chicago", "Pittsburgh", 3, "ec", 1),
    ("Chicago", "Cincinnati", 2, "ec", 1),
    ("Pittsburgh", "Lewisburg", 2, "ec", 2),
    ("Cincinnati", "Lewisburg", 3, "ec", 1),
    ("Cincinnati", "Knoxville", 2, "ec", 1),
    ("Cincinnati", "Nashville", 2, "ec", 1),
    ("Lewisburg", "Knoxville", 3, "ec", 1),
    ("Lewisburg", "Charlotte", 3, "ec", 1),
    ("Knoxville", "Nashville", 2, "ec", 1),
    ("Knoxville", "Atlanta", 2, "ec", 1),
    ("Knoxville", "Charlotte", 2, "ec", 1),
    ("Nashville", "Atlanta", 2, "ec", 1),
    ("Nashville", "Mobile", 3, "ec", 1),
    ("Atlanta", "Charlotte", 2, "ec", 1),
    ("Atlanta", "Charleston", 3, "ec", 1),
    ("Atlanta", "Mobile", 3, "ec", 1),
    ("Atlanta", "Savannah", 2, "ec", 1),
    ("Charlotte", "Charleston", 2, "ec", 1),
    ("Charleston", "Savannah", 2, "ec", 2),
    ("Mobile", "New Orleans", 2, "ec", 1),
    ("Mobile", "Savannah", 3, "ec", 1),
    # Florida
    ("Savannah", "Jacksonville", 2, "fl", 1),
    ("Jacksonville", "Miami", 3, "fl", 1),
    ("Jacksonville", "Tampa", 2, "fl", 2),
    ("Miami", "Tampa", 2, "fl", 1),
    ("Jacksonville", "Mobile", 3, "fl", 1),
    ("Mobile", "Tampa", 3, "fl", 1),
    # Great Plains
    ("Davenport", "Chicago", 2, "gp", 1),
    ("Davenport", "Kansas City", 2, "gp", 1),
    ("Davenport", "Omaha", 2, "gp", 2),
    ("Davenport", "St. Louis", 2, "gp", 1),
    ("Davenport", "St. Paul", 2, "gp", 1),
    ("Duluth", "Chicago", 3, "gp", 1),
    ("Duluth", "Fargo", 2, "gp", 1),
    ("Duluth", "St. Paul", 2, "gp", 1),
    ("Duluth", "Winnipeg", 3, "gp", 1),
    ("Kansas City", "Little Rock", 2, "gp", 1),
    ("Kansas City", "Oklahoma City", 2, "gp", 1),
    ("Kansas City", "Omaha", 2, "gp", 1),
    ("Kansas City", "St. Louis", 2, "gp", 1),
    ("Omaha", "St. Paul", 3, "gp", 1),
    ("St. Louis", "Chicago", 2, "gp", 1),
    ("St. Louis", "Cincinnati", 3, "gp", 1),
    ("St. Louis", "Nashville", 2, "gp", 1),
    ("St. Paul", "Chicago", 3, "gp", 1),
    # Open Range
    ("Dodge City", "Kansas City", 2, "or", 1),
    ("Dodge City", "Oklahoma City", 2, "or", 1),
    ("Dodge City", "Santa Fe", 3, "or", 1),
    ("Dallas", "El Paso", 3, "or", 1),
    ("Dallas", "Little Rock", 2, "or", 1),
    ("Dallas", "Oklahoma City", 2, "or", 1),
    ("Dallas", "Houston", 2, "or", 1),
    ("Dallas", "San Antonio", 2, "or", 2),
    ("Houston", "Little Rock", 3, "or", 1),
    ("Houston", "New Orleans", 2, "or", 1),
    ("Houston", "San Antonio", 2, "or", 1),
    ("Little Rock", "Nashville", 2, "or", 1),
    ("Little Rock", "New Orleans", 3, "or", 1),
    ("Little Rock", "Oklahoma City", 2, "or", 1),
    ("Little Rock", "St. Louis", 3, "or", 1),
    ("Oklahoma City", "Santa Fe", 3, "or", 1),
    # Badlands
    ("Fargo", "Miles City", 3, "bl", 1),
    ("Fargo", "St. Paul", 2, "bl", 1),
    ("Fargo", "Winnipeg", 2, "bl", 1),
    ("Miles City", "Regina", 2, "bl", 1),
    ("Miles City", "Winnipeg", 3, "bl", 1),
    ("Regina", "Winnipeg", 2, "bl", 1),
    # Haunted Wastes
    ("Cheyenne", "Denver", 2, "hw", 1),
    ("Cheyenne", "Fargo", 3, "hw", 1),
    ("Cheyenne", "Helena", 3, "hw", 1),
    ("Cheyenne", "Miles City", 2, "hw", 1),
    ("Cheyenne", "Omaha", 3, "hw", 1),
    ("Cheyenne", "Salt Lake City", 4, "hw", 1),
    ("Denver", "Dodge City", 3, "hw", 1),
    ("Denver", "Omaha", 3, "hw", 1),
    ("Denver", "Phoenix", 3, "hw", 1),
    ("Denver", "Salt Lake City", 2, "hw", 1),
    ("Denver", "Santa Fe", 2, "hw", 1),
    ("Phoenix", "Salt Lake City", 3, "hw", 1),
    ("Phoenix", "Santa Fe", 3, "hw", 1),
    ("Salt Lake City", "Spokane", 3, "hw", 1),
    # Cascadia
    ("Calgary", "Helena", 2, "cs", 1),
    ("Calgary", "Miles City", 2, "cs", 1),
    ("Calgary", "Regina", 3, "cs", 1),
    ("Calgary", "Spokane", 2, "cs", 1),
    ("Calgary", "Vancouver", 3, "cs", 1),
    ("Helena", "Miles City", 2, "cs", 1),
    ("Helena", "Salt Lake City", 3, "cs", 1),
    ("Helena", "Spokane", 2, "cs", 1),
    ("Portland", "Salt Lake City", 4, "cs", 1),
    ("Portland", "Seattle", 2, "cs", 1),
    ("Portland", "Spokane", 3, "cs", 1),
    ("Seattle", "Spokane", 3, "cs", 1),
    ("Seattle", "Vancouver", 1, "cs", 2),
    ("Spokane", "Vancouver", 3, "cs", 1),
    # California
    ("Nuevos Angeles", "Sacramento", 3, "ca", 1),
    ("Sacramento", "San Francisco", 2, "ca", 1),
    ("Sacramento", "Cemetery City", 2, "ca", 1),
    ("Sacramento", "Portland", 3, "ca", 1),
    ("San Francisco", "Pacific Haven", 2, "ca", 1),
    ("Pacific Haven", "Nuevos Angeles", 2, "ca", 1),
    ("Nuevos Angeles", "Baja", 2, "ca", 1),
    ("Nuevos Angeles", "Cemetery City", 2, "ca", 1),
    ("Cemetery City", "Baja", 2, "ca", 1),
    # Sierra Madre
    ("Chihuahua", "El Paso", 2, "sm", 1),
    ("Chihuahua", "Hermosillo", 2, "sm", 1),
    ("Chihuahua", "Monterrey", 2, "sm", 1),
    ("El Paso", "Hermosillo", 3, "sm", 1),
    ("El Paso", "Monterrey", 3, "sm", 1),
    ("El Paso", "Phoenix", 3, "sm", 1),
    ("El Paso", "San Antonio", 3, "sm", 1),
    ("El Paso", "Santa Fe", 3, "sm", 1),
    ("Hermosillo", "Phoenix", 3, "sm", 1),
    ("Monterrey", "San Antonio", 3, "sm", 1),
]

TICKETS = [
    ("EC-01", "ec", "Albany", "Bangor", 3),
    ("EC-02", "ec", "Albany", "Savannah", 8),
    ("EC-03", "ec", "Atlanta", "Philadelphia", 6),
    ("EC-04", "ec", "Baltimore", "New York", 2),
    ("EC-05", "ec", "Baltimore", "Savannah", 5),
    ("EC-06", "ec", "Boston", "Baltimore", 3),
    ("EC-07", "ec", "Buffalo", "Baltimore", 4),
    ("EC-08", "ec", "Buffalo", "Charleston", 6),
    ("EC-09", "ec", "Chicago", "Atlanta", 4),
    ("EC-10", "ec", "Chicago", "Baltimore", 5),
    ("EC-11", "ec", "Chicago", "Montreal", 6),
    ("EC-12", "ec", "Cincinnati", "Boston", 7),
    ("EC-13", "ec", "Cincinnati", "Mobile", 6),
    ("EC-14", "ec", "Detroit", "New Orleans", 9),
    ("EC-15", "ec", "Detroit", "New York", 5),
    ("EC-16", "ec", "Detroit", "Philadelphia", 4),
    ("EC-17", "ec", "Knoxville", "Norfolk", 5),
    ("EC-18", "ec", "Knoxville", "Savannah", 3),
    ("EC-19", "ec", "Mobile", "Boston", 11),
    ("EC-20", "ec", "Mobile", "Charlotte", 4),
    ("EC-21", "ec", "Montreal", "Philadelphia", 3),
    ("EC-22", "ec", "Montreal", "Quebec", 1),
    ("EC-23", "ec", "Nashville", "Charleston", 5),
    ("EC-24", "ec", "Nashville", "Montreal", 9),
    ("EC-25", "ec", "New Orleans", "Charleston", 6),
    ("EC-26", "ec", "New Orleans", "New York", 11),
    ("EC-27", "ec", "New Orleans", "Norfolk", 8),
    ("EC-28", "ec", "New York", "Boston", 1),
    ("EC-29", "ec", "Philadelphia", "Charleston", 5),
    ("EC-30", "ec", "Philadelphia", "New York", 1),
    ("EC-31", "ec", "Pittsburgh", "Bangor", 6),
    ("EC-32", "ec", "Pittsburgh", "Charlotte", 3),
    ("EC-33", "ec", "Quebec", "Savannah", 10),
    ("BL-05", "bl", "Fargo", "Chicago", 5),
    ("BL-13", "bl", "Miles City", "Baltimore", 14),
    ("BL-14", "bl", "Miles City", "New Orleans", 15),
    ("BL-08", "bl", "Regina", "Charleston", 16),
    ("BL-06", "bl", "Regina", "Fargo", 5),
    ("BL-07", "bl", "Regina", "New York", 17),
    ("BL-12", "bl", "Winnipeg", "Bangor", 15),
    ("BL-11", "bl", "Winnipeg", "Buffalo", 11),
    ("BL-09", "bl", "Winnipeg", "Cincinnati", 8),
    ("BL-10", "bl", "Winnipeg", "Savannah", 13),
    ("CA-19", "ca", "Baja", "Norfolk", 21),
    ("CA-21", "ca", "Baja", "Pittsburgh", 19),
    ("CA-22", "ca", "Cemetery City", "Charlotte", 18),
    ("CA-14", "ca", "Nuevos Angeles", "Atlanta", 18),
    ("CA-20", "ca", "Nuevos Angeles", "Detroit", 19),
    ("CA-15", "ca", "Nuevos Angeles", "Montreal", 23),
    ("CA-18", "ca", "Nuevos Angeles", "Nashville", 16),
    ("CA-13", "ca", "Nuevos Angeles", "New York", 23),
    ("CA-17", "ca", "Sacramento", "Albany", 21),
    ("CA-16", "ca", "Sacramento", "Knoxville", 18),
    ("CA-09", "ca", "Sacramento", "New Orleans", 18),
    ("CA-08", "ca", "San Francisco", "Baltimore", 21),
    ("CA-12", "ca", "San Francisco", "Chicago", 16),
    ("CA-11", "ca", "San Francisco", "Quebec", 23),
    ("CA-10", "ca", "San Francisco", "Savannah", 21),
    ("CS-11", "cs", "Calgary", "Chicago", 13),
    ("CS-10", "cs", "Calgary", "Mobile", 20),
    ("CS-13", "cs", "Helena", "Detroit", 14),
    ("CS-12", "cs", "Helena", "Knoxville", 15),
    ("CS-07", "cs", "Portland", "Cincinnati", 18),
    ("CS-06", "cs", "Portland", "Philadelphia", 23),
    ("CS-17", "cs", "Seattle", "Boston", 23),
    ("CS-05", "cs", "Seattle", "Buffalo", 20),
    ("CS-18", "cs", "Seattle", "Nashville", 18),
    ("CS-15", "cs", "Spokane", "Montreal", 20),
    ("CS-14", "cs", "Spokane", "Norfolk", 20),
    ("CS-09", "cs", "Vancouver", "Charleston", 23),
    ("CS-16", "cs", "Vancouver", "Helena", 5),
    ("CS-08", "cs", "Vancouver", "Pittsburgh", 21),
    ("FL-10", "fl", "Atlanta", "Tampa", 4),
    ("FL-08", "fl", "Boston", "Jacksonville", 9),
    ("FL-09", "fl", "Chicago", "Jacksonville", 7),
    ("FL-07", "fl", "Detroit", "Miami", 10),
    ("FL-06", "fl", "New Orleans", "Miami", 6),
    ("FL-05", "fl", "New York", "Miami", 10),
    ("FL-11", "fl", "Pittsburgh", "Tampa", 7),
    ("GP-12", "gp", "Davenport", "Charlotte", 7),
    ("GP-07", "gp", "Duluth", "Kansas City", 5),
    ("GP-10", "gp", "Duluth", "New Orleans", 11),
    ("GP-11", "gp", "Duluth", "Pittsburgh", 8),
    ("GP-09", "gp", "Kansas City", "Atlanta", 6),
    ("GP-08", "gp", "Kansas City", "Philadelphia", 9),
    ("GP-16", "gp", "Omaha", "Cincinnati", 4),
    ("GP-17", "gp", "Omaha", "Pittsburgh", 7),
    ("GP-14", "gp", "St. Louis", "Baltimore", 6),
    ("GP-15", "gp", "St. Louis", "Boston", 9),
    ("GP-13", "gp", "St. Louis", "Charleston", 6),
    ("GP-18", "gp", "St. Paul", "New York", 10),
    ("GP-06", "gp", "St. Paul", "Quebec", 10),
    ("GP-19", "gp", "St. Paul", "Savannah", 9),
    ("HW-13", "hw", "Cheyenne", "Montreal", 13),
    ("HW-12", "hw", "Cheyenne", "Pittsburgh", 11),
    ("HW-08", "hw", "Denver", "Atlanta", 10),
    ("HW-09", "hw", "Denver", "Knoxville", 10),
    ("HW-07", "hw", "Denver", "Norfolk", 14),
    ("HW-16", "hw", "Phoenix", "Bangor", 22),
    ("HW-15", "hw", "Phoenix", "Nashville", 13),
    ("HW-05", "hw", "Salt Lake City", "Mobile", 15),
    ("HW-14", "hw", "Salt Lake City", "Philadelphia", 17),
    ("HW-06", "hw", "Salt Lake City", "Santa Fe", 7),
    ("HW-11", "hw", "Santa Fe", "Boston", 17),
    ("HW-10", "hw", "Santa Fe", "Nashville", 9),
    ("OR-11", "or", "Dallas", "Buffalo", 11),
    ("OR-13", "or", "Dallas", "Montreal", 13),
    ("OR-12", "or", "Dallas", "New Orleans", 5),
    ("OR-10", "or", "Dallas", "New York", 12),
    ("OR-08", "or", "Dodge City", "Houston", 5),
    ("OR-09", "or", "Dodge City", "Pittsburgh", 9),
    ("OR-14", "or", "Houston", "Boston", 14),
    ("OR-16", "or", "Houston", "Charlotte", 8),
    ("OR-15", "or", "Houston", "Chicago", 9),
    ("OR-18", "or", "Little Rock", "Albany", 10),
    ("OR-17", "or", "Little Rock", "Philadelphia", 8),
    ("OR-19", "or", "Oklahoma City", "Baltimore", 10),
    ("OR-20", "or", "Oklahoma City", "Cincinnati", 6),
    ("OR-22", "or", "San Antonio", "Charleston", 11),
    ("OR-21", "or", "San Antonio", "Mobile", 6),
    ("SM-11", "sm", "Chihuahua", "Albany", 20),
    ("SM-12", "sm", "Chihuahua", "Chicago", 14),
    ("SM-07", "sm", "El Paso", "Charlotte", 14),
    ("SM-06", "sm", "El Paso", "Quebec", 19),
    ("SM-08", "sm", "Hermosillo", "Bangor", 23),
    ("SM-10", "sm", "Hermosillo", "Monterrey", 5),
    ("SM-09", "sm", "Hermosillo", "Savannah", 16),
    ("SM-13", "sm", "Monterrey", "Detroit", 13),
    ("SM-14", "sm", "Monterrey", "New Orleans", 7),
]

YEARS = [
    {"year": 1865, "game": 1, "trains": 20, "deal": 4, "keepMin": 2, "note": "Только Восточное побережье. 20 вагонов."},
    {"year": 1868, "game": 2, "trains": 20, "deal": 4, "keepMin": 2, "note": "Ещё 20 вагонов. После партии 1-е место открывает фронтир."},
    {"year": 1871, "game": 3, "trains": 20, "deal": 4, "keepMin": 2, "note": "Третья партия на 20 вагонах. Карта начинает расти."},
    {"year": 1874, "game": 4, "trains": 25, "deal": 4, "keepMin": 2, "note": "Вагоны добавляются по шкале на обороте коробки компании."},
    {"year": 1877, "game": 5, "trains": 30, "deal": 4, "keepMin": 2, "note": "Больше вагонов и билетов с новых регионов."},
    {"year": 1880, "game": 6, "trains": 34, "deal": 4, "keepMin": 2, "note": "Около 34 вагонов (шестая партия кампании)."},
    {"year": 1883, "game": 7, "trains": 40, "deal": 4, "keepMin": 2, "note": "Карта уже заметно шире исходной."},
    {"year": 1886, "game": 8, "trains": 45, "deal": 4, "keepMin": 2, "note": "Поздняя кампания, длинные трансконтинентальные билеты."},
    {"year": 1889, "game": 9, "trains": 50, "deal": 4, "keepMin": 2, "note": "Почти полный запас вагонов."},
    {"year": 1892, "game": 10, "trains": 52, "deal": 4, "keepMin": 2, "note": "Десятая партия."},
    {"year": 1895, "game": 11, "trains": 56, "deal": 4, "keepMin": 2, "note": "Полный запас: 56 вагонов на игрока."},
    {"year": 1898, "game": 12, "trains": 56, "deal": 4, "keepMin": 2, "note": "Финал кампании. 56 вагонов."},
    {"year": 1901, "game": 13, "trains": 56, "deal": 5, "keepMin": 3, "note": "Посткампания: все билеты возвращаются, раздача 5, оставить ≥3."},
]


def route_id(a, b):
    x, y = sorted([a, b])
    return f"{x}|{y}"


def build_payload():
    cities = []
    for name, meta in CITIES.items():
        cities.append({"id": name, **meta})
    routes = []
    for a, b, length, region, tracks in ROUTES:
        routes.append({
            "id": route_id(a, b),
            "a": a,
            "b": b,
            "length": length,
            "region": region,
            "tracks": tracks,
        })
    tickets = []
    for code, region, a, b, value in TICKETS:
        tickets.append({
            "id": code,
            "region": region,
            "a": a,
            "b": b,
            "value": value,
        })
    return {
        "regions": REGIONS,
        "cities": cities,
        "routes": routes,
        "tickets": tickets,
        "years": YEARS,
        "trainRemainderBonus": [
            {"left": [0], "dollars": 16},
            {"left": [1], "dollars": 12},
            {"left": [2], "dollars": 9},
            {"left": [3], "dollars": 6},
            {"left": [4], "dollars": 4},
            {"left": [5, 6, 7], "dollars": 2},
            {"left": [8, 9, 10], "dollars": 1},
            {"left": [11], "dollars": 0},
        ],
        "rules": {
            "players": [2, 3, 4, 5],
            "startCash": 5,
            "startTrainCards": 4,
            "newspapers": {2: 6, 3: 4, 4: 3, 5: 3},
            "doubleRoutesLockedIfPlayersAtMost": 3,
            "notes": [
                "В начале партии раздают 4 билета, оставить нужно минимум 2 (в 1901: 5 и минимум 3).",
                "Добирать билеты можно ходом: 3 штуки, оставить ≥1.",
                "Очки за билет — напечатанные доллары; незакрытый билет вычитается.",
                "Вагоны за маршруты очков не дают — только за билеты, цвет компании, события и остаток вагонов.",
                "В партиях на 2–3 игроков из двойного маршрута доступен только один путь.",
                "Регионы открывает победитель (иногда проигравший) — состав карты не фиксирован годом.",
            ],
        },
    }
